# settings for domain of waveforms
domain_settings:
  name: UniformFrequencyDomain
  kwargs:
    f_min: 10.0
    f_max: 1024.0
    delta_f: 1.0/8.0
    f_ref: 20.0
    window_factor: 1.0 # this should maybe be in noise settings?

# settings for waveform generator
waveform_generator_settings:
  approximant: SEOBNRv4PHM
  f_ref: 20.0

# settings for prior over parameters
prior_settings:
  # prior for intrinsic parameters of the dataset
  intrinsic_parameters:
    mass_1: [Uniform, 10, 80]
    mass_2: [Uniform, 10, 80]
    phase: default
    a_1: [Uniform, 0, 0.88]
    a_2: [Uniform, 0, 0.88]
    tilt_1: default
    tilt_2: default
    phi_12: default
    phi_jl: default
    theta_jn: default
  # reference values for extrinsic parameters
  # all non-specified ones will be set to zero
  extrinsic_parameters_reference_values:
    luminosity_distance: 100.0
  # indices for parameters in waveform_dataset.hdf5['parameters']
  # parameters should not be stored as dicts, since this is less efficient
  parameter_indices:
    mass_1: 0
    mass_2: 1
    phase: 2
    t_c: 3
    luminosity_distance: 4
    a_1: 5
    a_2: 6
    tilt_1: 7
    tilt_2: 8
    phi_12: 9
    phi_jl: 10
    theta_jn: 11
    psi: 12
    ra: 13
    dec: 14